// SPDX-FileCopyrightText: 2022 Linblow <dev@linblow.com>
// SPDX-License-Identifier: BSD-3-Clause
#include <common/psp/types.h>
#include <test_sce_printf/config.h>

#ifndef APP_ATTR
#define APP_ATTR (0)
#endif

#if KERNEL_MODULE
SCE_MODULE_INFO(APP_NAME, SCE_MODULE_KERNEL | APP_ATTR, APP_VER_MAJOR, APP_VER_MINOR);
#else
SCE_MODULE_INFO(APP_NAME, APP_ATTR, APP_VER_MAJOR, APP_VER_MINOR);
#endif

#ifndef START_STOP_INITPRIO
#define START_STOP_INITPRIO (16)
#endif

#ifndef START_STOP_STACKSZ
#define START_STOP_STACKSZ (1*1024)
#endif

#ifndef START_STOP_ATTR
# if KERNEL_MODULE
#  define START_STOP_ATTR (0)
# else
#  define START_STOP_ATTR (SCE_KERNEL_TH_USER_MODE)
# endif
#endif

#if USE_START_STOP_THREAD_PARAMETER
SCE_MODULE_START_THREAD_PARAMETER(3, START_STOP_INITPRIO, START_STOP_STACKSZ, START_STOP_ATTR);
SCE_MODULE_STOP_THREAD_PARAMETER(3, START_STOP_INITPRIO, START_STOP_STACKSZ, START_STOP_ATTR);
#endif /* USE_START_STOP_THREAD_PARAMETER */
